# 应用服务 WEB 访问端口
server:
  port: 8089
  servlet:
    context-path: /myframe

spring:
  application:
    name: myframe
  # mysql配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/frametable?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    show-sql: true
    format_sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    database: mysql

  redis:
    port: 6379
    host: localhost
    database: 0


# lombok配置
lombok:
  equalsAndHashCode:
    callSuper: call




# mybatis配置
#mybatis:
#    mapper-locations: classpath:mapper/*Mapper.xml
#    configuration:
#      # 驼峰映射
#      map-underscore-to-camel-case: true

# 打印sql参数
logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: trace
